remote_theme: pages-themes/leap-day@v0.2.0
url: https://asaragga.github.io/FinCalc
plugins:
- jekyll-remote-theme 
title: Law and Money Matters
description: Financial Analysis and Computations for Solicitors
