remote_theme: pages-themes/leap-day@v0.2.0
url: https://asaragga.github.io/FinCalcPT
plugins:
- jekyll-remote-theme 
title: Cálculo Financeiro para Solicitadores
description: Tópicos na Interseção entre Direito & Finanças
